### ISSUE TITLE
Sentry for backend 

### ISSUE THREAD

**Issue by jacksbox** [bcye/lokalshoppen#11]

**Comment by bcye** [comment]
Das Backend kann schon so automatisiert emails, an eine vordefinierte liste an admins schicken mit jeglichen Fehlern die aufkommen. Ich denke nicht das Sentry hier notwendig ist.

**Comment by jacksbox** [comment]
kein must have für jetzt, aber (in der Zukunft) auf Dauer angenehmer :)

**Comment by bcye** [comment]
wenn du meinst kann ich es gerne schnell einrichten, ist ja nur mehr oder weniger ein command.

**Comment by bcye** [comment]
Ist eingerichtet
